server:
  port: 8085
spring:
  application:
    name: data-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springPractice
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update



logging:
  level:
    org.springframework.cloud.logging: TRACE